insert into alumnos (cedula, nombre, apellido, nacimiento) values('4757679', 'David', 'Bareiro', '1997-08-12');
insert into alumnos (cedula, nombre, apellido, nacimiento) values('1236478', 'Melissa', 'Quiñonez', '1987-11-28');
insert into alumnos (cedula, nombre, apellido, nacimiento) values('7382992', 'Pedro', 'Perez', '1996-02-01');
insert into alumnos (cedula, nombre, apellido, nacimiento) values('4325666', 'Ana', 'Vera', '1977-05-19');
insert into alumnos (cedula, nombre, apellido, nacimiento) values('3425627', 'Johanna', 'Mereles', '1977-10-09');
insert into alumnos (cedula, nombre, apellido, nacimiento) values('4235267', 'Mario', 'Benitez', '1967-07-23');

insert into profesores (cedula, nombre, apellido) values('2132435', 'David', 'Gaona');
insert into profesores (cedula, nombre, apellido) values('3000323', 'Zunilda', 'Fernandez');
insert into profesores (cedula, nombre, apellido) values('4585799', 'Pablo', 'Cardozo');
insert into profesores (cedula, nombre, apellido) values('7364667', 'Joseph', 'Chong');
insert into profesores (cedula, nombre, apellido) values('6374888', 'Sarah', 'Cabrera');
insert into profesores (cedula, nombre, apellido) values('4637833', 'Pedro', 'Pedrozo');
insert into profesores (cedula, nombre, apellido) values('4639999', 'Marcos', 'Zeballos');
insert into profesores (cedula, nombre, apellido) values('2388283', 'Cesia', 'Estrada');
insert into profesores (cedula, nombre, apellido) values('4423232', 'Mariela', 'Britez');
insert into profesores (cedula, nombre, apellido) values('5263777', 'Mercedez', 'Mercado');
insert into profesores (cedula, nombre, apellido) values('5537890', 'Sofia', 'Speratti');
insert into profesores (cedula, nombre, apellido) values('2399900', 'Ximena', 'Garcia');
insert into profesores (cedula, nombre, apellido) values('7994809', 'Marcelino', 'Recalde');
insert into profesores (cedula, nombre, apellido) values('4300921', 'Hector', 'Arias');
insert into profesores (cedula, nombre, apellido) values('5537890', 'Rodrigo', 'Vera');

insert into asignaturas (descripcion) values('Matematica Basica');
insert into asignaturas (descripcion) values('Aritmetica');
insert into asignaturas (descripcion) values('Algebra');
insert into asignaturas (descripcion) values('Geometria Basica');
insert into asignaturas (descripcion) values('Geometria Avanzada');
insert into asignaturas (descripcion) values('Trigonometria');
insert into asignaturas (descripcion) values('Fisica');
insert into asignaturas (descripcion) values('Quimica');
insert into asignaturas (descripcion) values('Geometria Analitica');
insert into asignaturas (descripcion) values('Calculo Diferencial');
insert into asignaturas (descripcion) values('Estadisticas y Proabilidades');
insert into asignaturas (descripcion) values('Ingles Basico');
insert into asignaturas (descripcion) values('Ingles Intermedio');
insert into asignaturas (descripcion) values('Ingles Avanzado');
insert into asignaturas (descripcion) values('Introduccion a la Programacion');
insert into asignaturas (descripcion) values('Algoritmica Estructurada');
insert into asignaturas (descripcion) values('Algoritmica Avanzada');
insert into asignaturas (descripcion) values('Diseño de Base de Datos');
insert into asignaturas (descripcion) values('Base de Datos Modulo I');
insert into asignaturas (descripcion) values('Base de Datos Modulo II');
insert into asignaturas (descripcion) values('Teoria de Redes');
insert into asignaturas (descripcion) values('Aplicacion de Redes Informaticas');
insert into asignaturas (descripcion) values('Diseño Grafico y Marketing');
insert into asignaturas (descripcion) values('Animacion en 3D Modulo I');
insert into asignaturas (descripcion) values('Animacion en 3D Modulo II');
insert into asignaturas (descripcion) values('Animacion en 3D Modulo III');